"""Generate app.html (one screen per URL: app.html?skin=b|c&id=<screen>#<screen>) from index.html + skins.css.
Edit index.html (the phones) or skins.css, then run: python3 design/concept-prototypes/redesign/build_app.py"""
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
src = (HERE / "index.html").read_text()
style = re.search(r"<style>(.*?)</style>", src, re.S).group(1)
svg = re.search(r'(<svg width="0".*?</svg>)', src, re.S).group(1)
tpls = re.search(r'(<template id="tabbar">.*?</template>\s*<template id="bar">.*?</template>)', src, re.S).group(1)
ids = ["owner-home", "owner-bookings", "owner-feed", "owner-diary", "owner-mood", "sitter-home"]
phones = []
for m in re.finditer(r'<div class="phone"', src):
    depth = 0
    for t in re.finditer(r"<div\b|</div>", src[m.start():]):
        depth += 1 if t.group().startswith("<div") else -1
        if depth == 0:
            phones.append(src[m.start(): m.start() + t.end()])
            break
assert len(phones) == len(ids), len(phones)
room = ('<div class="pixel-room" aria-label="Max status room"><div class="hud"><span>❤️❤️❤️</span><span>🍖 full</span></div>'
        '<span class="bowl">🥣</span><canvas width="24" height="24" data-src="img/pet0.jpg"></canvas><span class="ball">🎾</span></div>')
phones[5] = phones[5].replace('<div class="scroll" style="gap:12px">', '<div class="scroll" style="gap:12px">' + room, 1)
body = "\n".join(f'<template id="s-{k}">{p}</template>' for k, p in zip(ids, phones))
# Expressive (skin=d) has its own layouts in expressive.html, plus the illustration sprite art.svg.
xsrc = (HERE / "expressive.html").read_text()
xstyle = re.search(r"<style>(.*?)</style>", xsrc, re.S).group(1)
xicons = re.search(r'(<svg width="0".*?</svg>)', xsrc, re.S).group(1)
art = (HERE / "art.svg").read_text()
for m in re.finditer(r'<div class="xp" data-id="([a-z-]+)">', xsrc):
    depth = 0
    for t in re.finditer(r"<div\b|</div>", xsrc[m.start():]):
        depth += 1 if t.group().startswith("<div") else -1
        if depth == 0:
            body += f'\n<template id="x-{m.group(1)}">{xsrc[m.start(): m.start() + t.end()]}</template>'
            break
script = """<script>
  addEventListener("hashchange", () => location.reload());
  const skin = new URLSearchParams(location.search).get("skin");
  if (skin) document.documentElement.dataset.skin = skin;
  const id = location.hash.slice(1) || "owner-home";
  const t = (skin === "d" && document.getElementById("x-" + id)) || document.getElementById("s-" + id) || document.getElementById("s-owner-home");
  const out = document.getElementById("out"); out.appendChild(t.content.cloneNode(true));
  out.querySelectorAll(".phone").forEach((p) => {
    const bar = document.getElementById("bar").content.cloneNode(true);
    bar.querySelector("h4").textContent = p.dataset.title;
    if (p.dataset.ava) bar.querySelector(".ava").textContent = p.dataset.ava;
    p.prepend(bar);
    const tabs = document.getElementById("tabbar").content.cloneNode(true);
    tabs.querySelector(`[data-t="${p.dataset.tab}"]`).classList.add("on");
    p.append(tabs);
  });
  out.querySelectorAll(".pixel-room canvas").forEach((c) => {
    const img = new Image(); img.onload = () => { const x = c.getContext("2d"); x.imageSmoothingEnabled = false;
      const s = Math.min(img.width, img.height); x.drawImage(img, (img.width - s) / 2, (img.height - s) / 4, s, s, 0, 0, 24, 24); };
    img.src = c.dataset.src;
  });
</script>"""
html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Goldito Redesign Screen</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lilita+One&family=Inter:wght@400;500;600;700;800&family=Fredoka:wght@500;600&family=Nunito:wght@400;600;700&family=Plus+Jakarta+Sans:wght@400;600;700;800&display=swap">
<!-- Generated by build_app.py from index.html + skins.css. -->
<style>{style}
html,body{{margin:0;padding:0;background:transparent}}
body{{padding:0!important}}
.phone{{width:402px!important;max-width:none;height:874px!important;border:0!important;border-radius:0!important}}
{xstyle}
</style>
<link rel="stylesheet" href="skins.css">
<script src="../nav.js" defer></script>
</head><body>
{svg}
{xicons}
{art}
{tpls}
{body}
<div id="out"></div>
{script}
</body></html>"""
(HERE / "app.html").write_text(html)
print("app.html written")
